Foosball/app/models.py
import flask
from . import db


class Team(db.Model):
    __tablename__ = 'teams'
    t_id = db.Column(db.Integer, primary_key=True)
    team_name = db.Column(db.String(50))
    city = db.Column(db.String(50))
    users = db.relationship('User',backref='teams')

    def __repr__(self):
        return '<Team %r>' % self.team_name

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()
        return self.t_id
    
    @staticmethod
    def id_to_name(num):
        name = Team.query.filter_by(team_id=num).first()
        return name.team_name

    @staticmethod
    def name_to_id(name):
        name = Team.query.filter_by(team_name=name).first()
        return name.t_id

    @staticmethod
    def display_teams_data():
        data = db.engine.execute(
            '''SELECT team_name, COUNT(CASE WHEN NULL THEN 0 ELSE users.email END), city
            FROM teams LEFT JOIN users
            ON teams.t_id = users.team_id
            GROUP BY team_name
            ORDER BY team_name COLLATE NOCASE ASC''')
        display_data = {}
        for element in data:
            display_data[str(element[0])] = element[1], element[2]
        return display_data


class User(db.Model):
    __tablename__ = 'users'
    email = db.Column(db.String(128), primary_key=True)
    name = db.Column(db.String(128))
    team_id = db.Column(db.Integer, db.ForeignKey('teams.t_id'), nullable=True)

    def __repr__(self):
        return '<User %r>' % self.name
    
    def join_team(self, team_id):
        self.team_id = team_id

    def leave_team(self, team_id):
        self.team_id = None

    @staticmethod
    def current_user():
        return User.query.filter_by(
        email=flask.session['user_info']['emails']).first()

   

Foosball/app/main/forms.py
from ..models import User, Team
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired

class NewTeam(FlaskForm):
    name = StringField('TEAM NAME', validators=[InputRequired("Required")])
    city = StringField('CITY', validators=[InputRequired("Required")])
    submit = SubmitField('Add New Team')

Foosball/app/__init__.py
import flask
from flask_sqlalchemy import SQLAlchemy
from config import config

db = SQLAlchemy()

def create_app(config_name):
    """
    Application factory. Takes the name of a configuration to use for 
    application. Returns created application instance.
    """
    app = flask.Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)

    #routes attachement
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    

    return app

Foosball/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

Foosball/app/main/views.py
"""
 We Foosball
    ~~~~~~
    A simple web application written with Flask + sqlite3 + SQLAlchemy.
    Photo credit: Thomas Serer on Unsplash (https://unsplash.com/photos/r-xKieMqL34)

"""
import os
from sqlite3 import dbapi2 as sqlite3
import flask
from . import main
from .. import db
from ..models import User, Team
from .forms import NewTeam
import json


@main.route('/', methods = ['GET', 'POST'])
def index():
    return flask.render_template('index.html')


@main.route('/register', methods = ['GET', 'POST'])
def register():
    return flask.render_template('register.html')


@main.route('/teams', methods = ['GET', 'POST'])
def teams():
    if 'credentials' not in flask.session:
      return flask.redirect('register')
    teams = Team.display_teams_data()
    user_info = User.query.group_by(User.team_id).all()
    return flask.render_template(
        'teams.html', teams=teams, user_info=user_info)


@main.route('/teams/<name>')
def team(name):
    if 'credentials' not in flask.session:
      return flask.redirect('register')
    try:
        eligibile_member = User.current_user()
        team_data = Team.query.filter_by(team_name=name).first()
        members = User.query.filter_by(team_id=team_data.t_id).all()
        if len(members) == 0:
            db.session.delete(team_data)
            db.session.commit()
            return flask.render_template('deleted.html', name=name)
        return flask.render_template(
            'team.html', name=name, team=team_data, members=members,
            number = len(members), eligibile=eligibile_member)
    except:
        return flask.redirect('teams')


@main.route('/teams/<name>/join')
def jointeam(name):
    if 'credentials' not in flask.session:
      return flask.redirect('register')
    current_user = User.current_user()
    team_id = Team.name_to_id(name)
    members = User.query.filter_by(team_id=team_id).all()
    if (current_user.team_id == None) and (len(members)) < 4:
        current_user.join_team(team_id)
    return flask.redirect('teams/' + name)


@main.route('/teams/<name>/leave')
def leaveteam(name):
    if 'credentials' not in flask.session:
      return flask.redirect('register')
    current_user = User.current_user()
    team_id = Team.name_to_id(name)
    if current_user.team_id == team_id:
        current_user.leave_team(team_id)
    return flask.redirect('teams/' + name)


@main.route('/teams/newteam', methods = ['GET', 'POST'])
def newteam():
    if 'credentials' not in flask.session:
      return flask.redirect('register')
    # Check if a user belongs to any team already.
    eligibile_member = User.current_user()
    # Allow a user to create a new team if he/she doesn't belong to any team.
    if eligibile_member.team_id == None:
        name, city = None, None
        form = NewTeam()
        if form.validate_on_submit():
            # Check whether selected team name is already taken.
            check_name_av = Team.query.filter_by(
                team_name=form.name.data).first()
            if check_name_av != None:
                flask.flash("Seems like you selected a team name already in use.")
                return flask.render_template(
                    'newteam.html', form=form, name=name, city=city)
            else:
                # Add a new team and add it's creator as a first member.
                new_team = Team(team_name=form.name.data, city=form.city.data)
                id_of_new_team = new_team.save_to_db()
                eligibile_member.join_team(id_of_new_team)
                return flask.redirect(flask.url_for('main.teams'))
        return flask.render_template(
            'newteam.html', form=form, name=name, city=city)
    else:
        teamname = Team.query.filter_by(t_id=eligibile_member.team_id).first()
        return flask.render_template('double.html', teamname=teamname.team_name)

Foosball/app/templates/base.html
<!DOCTYPE html>
<html lang='en'>
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Homemade+Apple" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../static/styles.css"> 
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

Foosball/app/templates/deleted.html
{% extends "base.html" %}
{% block title %}{{ name }}{% endblock %}
{% block body %}
  <div class='container'>
    <div class='deleted text-center'>
      <p>Last member left {{ name }} - the group has been deleted.</p>
      <div class='text-center'>
        <a href='/teams'>Return to Teams</a>
        <a href="{{url_for('auth.logout')}}">LogOut</a>
      </div>
    </div>
  </div>
{% endblock %}

Foosball/app/templates/double.html
{% extends "base.html" %}
{% block title %}Member Already{% endblock %}
{% block body %}
  <div class='container'>
    <div class='double text-center'>
      <p>You are already member of {{ teamname }}</p>
      <p class='instructions'>Sorry, but you can be a memember of one team only. Leave your current team
      to create or join other.</p>
      <a href='/teams'>Return to Teams</a>
      <a href="{{url_for('auth.logout')}}">LogOut</a>
    </div>
  </div>
{% endblock %}

Foosball/app/templates/index.html
{% extends "base.html" %}
{% block title %}We Foosball App{% endblock %}
{% block body %}
  <body class='home'>
    <div class="container">
      <div class='homeMain text-center'>
        <h1>We Foosball</h1>
        <h2>Find Your Dream Team to Play Foosball</h2>
        <a href="{{url_for('auth.authorize')}}">Log In with Google</a>
      </div>
    </div>
  </body>
{% endblock %}





 

Foosball/app/templates/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock %}
{% block body %}
  <div class='container'>
    <div class='logout text-center'>
      <p>You have been logged out successfully.</p>
      <p>Before using We Foosball again please log in with Google</p>
      <p>Hope to see you again soon.</p>
      <a href="{{url_for('auth.authorize')}}">Login with Google</a>
      <a href="{{url_for('main.index')}}">Home</a>
    </div>
  </div>
{% endblock %}

Foosball/app/templates/newteam.html
{% extends "base.html" %}
{% block title %}New Team{% endblock %}
{% block body %}
  <div class='container'>
    <div class='newteam'>
      <h3 class='instructions text-center'>Instructions</h3>
      <p class='instructions'>To add a new team choose a team name. It may not 
      be longer than 20 characters. You will be automatically added to your 
      team as a member. You can be a member of one team only so make wise 
      choices. Name of a team has to be unique.</p>
      <form method="POST" class='teamForm'>
        {{ form.csrf_token }}
        <div>
          <div>{{ form.name.label }}</div>
          <div class='inpField'>{{ form.name() }}</div>
          <div class='inpField'>
          {% if form.name.errors %}
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
          </div>
        </div>
        <div>
          <div>{{ form.city.label }}</div>
          <div class='inpField'>{{ form.city() }}</div>
          <div class='inpField'>
          {% if form.city.errors %}
            {% for error in form.city.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
          </div>
        </div>
        {% with messages = get_flashed_messages() %} <!--When the same name used -->
          {% if messages %} 
            <p class='message'>{{ messages[-1] }}</p>
          {% endif %}
        {% endwith %}
        <div id='addTeam' class='text-center'>{{ form.submit(class='submitCont') }}</div>
      </form>
      <div class='returnButtons text-center'>
        <a href='/teams'>Return to Teams</a>
        <a href="{{url_for('auth.logout')}}">LogOut</a>
      </div>
    </div>
  </div>
{% endblock %}

Foosball/app/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block body %}
  <div class='container'>
    <div class='register text-center'>
      <h1>We Foosball</h1>
      <p>To use our service you have to log in with Google.</p>
      <a href="{{url_for('auth.authorize')}}">Log with Google</a>
    </div>
  </div>
{% endblock %}

Foosball/app/templates/team.html
{% extends "base.html" %}
{% block title %}{{ name }}{% endblock %}
{% block body %}
  <div class='container'>
    <div class='singleTeam text-center'>
      <h1>Welcome to {{ name }}</h1>
      <p>We shake {{ team.city}}. We are in {{ number }} already.</p>
      <p>You can join us only if you don't belong elsewhere.</p>
      <h2>Our Members</h2>
      <table>
        <tr>
          <th>Name</th>
          <th>Email</th>
        </tr>
        {% for member in members %}
          <tr>
            <td>{{ member.name }}</td> 
            <td>{{ member.email }}</td>
          </tr>
        {% endfor %}
      </table>
      {% if number < 4 and eligibile.team_id == None %}
        <a href='/teams/{{ name }}/join'>Join</a>
      {% endif %}
      {% if eligibile.team_id == team.t_id %}
        <a href='/teams/{{ name }}/leave'>Sign out of {{ name }}</a>
      {% endif %}
      <a href='/teams'>Return to Teams</a>
      <a href="{{url_for('auth.logout')}}">LogOut</a>
    </div>
  </div>
{% endblock %}




  

Foosball/app/templates/teams.html
{% extends "base.html" %}
{% block title %}Teams{% endblock %}
{% block body %}
  <div class='container'>
    <div class='teams text-center'>
      <h1>Our Teams</h1>
      {% if teams %}
        <table class='text-left'> 
          <tr>
            <th>Team Name</th>
            <th>City</th>
            <th>Members</th>
          </tr>
          {% for team in teams %}
            <tr>
              <td><a class='teams' href="/teams/{{team}}">{{team}}</a></td>
              <td>{{teams[team][1]}}</td>
              <td>{{teams[team][0]}}</td>
            </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>There are no teams to join at the moment.</p>
      {% endif %}
      <p>Join the team or create one yourself. You can be member of one 
      team only so make wise choice.</p>
      <a href="{{url_for('main.newteam')}}">Add New Team</a>
      <a href="{{url_for('auth.logout')}}">LogOut</a>
    </div>
  </div>
{% endblock %}